__default__:
    time: 2:00:00
    mem: 2G
    email: lswhiteh@unc.edu
    email_type: "FAIL"
    output: "logs_snakemake/{rule}.{wildcards}.out"
    cluster: sbatch
    jobs: 200 
    conda: "../../blinx.yml"

createBatchNpz:
    time: 2-00:00:00
    mem: 64G
    cores: 8

mergeNpzs:
    time: 2-00:00:00
    mem: 256G
    cores: 2
