base_sim_dir: /pine/scr/l/s/lswhiteh/timeSeriesSweeps/onePop-selectiveSweep/sims
schema_name: dense_modern_20samp
sample_size: 20
samp_gens: 0 8 16 22 28 32 36 38 39 40
num_timepoints: None
max_timepoints: 41